import cuid from 'cuid'

export default function manageRestaurant(state = {restaurants: []}, action){

  switch (action.type) {
    case 'ADD_RESTAURANT':
    //let restaaurant have an id generated by cuid, and the name as restaurant.name entered on the form

    //return a copy of all of the state, but only update the restaurants array by using the spread operator to make a copy of it and pass in our new restaurant
      let restaurant = {
        id: cuid(),
        name: action.payload.name
      }
      return this.props.addRestaurant(restaurant)

    default:
      return state
  }
}
